/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 8680213
 */
public class Cliente_CL extends javax.swing.JFrame {
    
    
    public PreparedStatement pst;
    public Connection con;
    public Statement st;
    public String estado_cliente;
    public int idcliente;
    Conexao CL_Cliente = new Conexao ();
    Cliente c = new Cliente();
    /**
     * Creates new form Cliente
     */
    public Cliente_CL() {
        initComponents();
    
        CL_Cliente.conexao();
        CL_NOME.setEnabled(false);
        CL_RG.setEnabled(false);
        CL_CPF.setEnabled(false);
        CL_DATA_NASCIMENTO.setEnabled(false);
        CL_RUA.setEnabled(false);
        CL_NUMERO.setEnabled(false);
        CL_BAIRRO.setEnabled(false);
        CL_CEP.setEnabled(false);
        CL_CIDADE.setEnabled(false);
        CL_ESTADO.setEnabled(false);
        CL_EMAIL.setEnabled(false);
        CL_DATA_CADASTRO.setEnabled(false);
        CL_TELEFONE_FIXO.setEnabled(false);
        CL_CELULAR_1.setEnabled(false);
        CL_CELULAR_2.setEnabled(false);
        CL_CELULAR_3.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CL_NOME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CL_RG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CL_CPF = new javax.swing.JTextField();
        label_dataNascimento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CL_BAIRRO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CL_RUA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CL_CIDADE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CL_CEP = new javax.swing.JTextField();
        CL_EMAIL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CL_TELEFONE_FIXO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CL_CELULAR_3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CL_DATA_CADASTRO = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        CL_NUMERO = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CL_ESTADO = new javax.swing.JTextField();
        CL_CELULAR_2 = new javax.swing.JTextField();
        CL_CELULAR_1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CL_DATA_NASCIMENTO = new javax.swing.JFormattedTextField();
        CL_STATUS = new javax.swing.JCheckBox();
        btn_pesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(CL_NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 400, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("RG:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(CL_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));
        jPanel1.add(CL_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 170, -1));

        label_dataNascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_dataNascimento.setText("Data Nascimento :");
        jPanel1.add(label_dataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel1.add(CL_BAIRRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Rua:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(CL_RUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 320, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        jPanel1.add(CL_CIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));
        jPanel1.add(CL_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 170, -1));
        jPanel1.add(CL_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Celular");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        jPanel1.add(CL_TELEFONE_FIXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 120, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Telefone Fixo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));
        jPanel1.add(CL_CELULAR_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Data de Cadastro:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        CL_DATA_CADASTRO.setEditable(false);
        jPanel1.add(CL_DATA_CADASTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 80, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Foto");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 70, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Código Cliente:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jTextField25.setEditable(false);
        jPanel1.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 50, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Novo");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 90, 20));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Gravar");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, 90, 20));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Alterar");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 680, 90, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, 70, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Nº");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));
        jPanel1.add(CL_NUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Estado");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));
        jPanel1.add(CL_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 40, -1));
        jPanel1.add(CL_CELULAR_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 120, -1));
        jPanel1.add(CL_CELULAR_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DADOS PESSOAIS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("ENDEREÇO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CONTATO");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        try {
            CL_DATA_NASCIMENTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CL_DATA_NASCIMENTO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(CL_DATA_NASCIMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 110, -1));

        CL_STATUS.setBackground(new java.awt.Color(255, 255, 204));
        CL_STATUS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CL_STATUS.setText("ATIVO");
        CL_STATUS.setContentAreaFilled(false);
        CL_STATUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CL_STATUSActionPerformed(evt);
            }
        });
        jPanel1.add(CL_STATUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 80, 40));

        btn_pesquisa.setText("Pesquisar");
        btn_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 530, 150));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fundo_cliente.jpg"))); // NOI18N
        jLabel20.setAutoscrolls(true);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 650, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipal2 obj = new MenuPrincipal2();
        obj.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        if("1".equals(estado_cliente))
        {
        try{
       PreparedStatement pst = CL_Cliente.con.prepareStatement("insert into CLIENTE_1"
       +"(CL_NOME,CL_RG,CL_CPF,CL_DATA_NASCIMENTO,CL_RUA,CL_NUMERO,CL_BAIRRO,CL_CEP,CL_CIDADE,CL_ESTADO,CL_STATUS,CL_EMAIL,CL_DATA_CADASTRO)values(?,?,?,?,?,?,?,?,?,?,?,?,GETDATE())" );
       pst.setString(1,CL_NOME.getText());
       pst.setString(2,CL_RG.getText());
       pst.setString(3,CL_CPF.getText());
       pst.setString(4,CL_DATA_NASCIMENTO.getText());
       pst.setString(5,CL_RUA.getText());
       pst.setString(6,CL_NUMERO.getText());
       pst.setString(7,CL_BAIRRO.getText());
       pst.setString(8,CL_CEP.getText());
       pst.setString(9,CL_CIDADE.getText());
       pst.setString(10,CL_ESTADO.getText()); 
       pst.setString(11,CL_STATUS.getText());
       pst.setString(12,CL_EMAIL.getText());
       PreparedStatement pstTel = CL_Cliente.con.prepareStatement("insert into CLIENTE_TELEFONE (CL_TELEFONE_FIXO,CL_CELULAR_1,"
       +"CL_CELULAR_2,CL_CELULAR_3)VALUES (?,?,?,?)");
       pstTel.setString(1,CL_TELEFONE_FIXO.getText());
       pstTel.setString(2,CL_CELULAR_1.getText());
       pstTel.setString(3,CL_CELULAR_2.getText());
       pstTel.setString(4,CL_CELULAR_3.getText());
       pst.executeUpdate();
       pstTel.executeUpdate();
       JOptionPane.showMessageDialog(null,"Cliente Cadastrado com Sucesso!");
       }catch(Exception e)
        {
       JOptionPane.showMessageDialog(null,"ERRO NA INSERÇAO ! \n ERRO : " +e);    
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null," Cliente dever ser Ativado");
        }
        CL_NOME.setEnabled(false);CL_NOME.setText("");
        CL_RG.setEnabled(false);CL_RG.setText("");
        CL_CPF.setEnabled(false);CL_CPF.setText("");
        CL_DATA_NASCIMENTO.setEnabled(false);CL_DATA_NASCIMENTO.setText("");
        CL_RUA.setEnabled(false);CL_RUA.setText("");
        CL_NUMERO.setEnabled(false);CL_NUMERO.setText("");
        CL_BAIRRO.setEnabled(false);CL_BAIRRO.setText("");
        CL_CEP.setEnabled(false);CL_CEP.setText("");
        CL_CIDADE.setEnabled(false);CL_CIDADE.setText("");
        CL_ESTADO.setEnabled(false);CL_ESTADO.setText("");
        CL_EMAIL.setEnabled(false);CL_EMAIL.setText("");
        CL_DATA_CADASTRO.setEnabled(false);CL_DATA_CADASTRO.setText("");
        CL_TELEFONE_FIXO.setEnabled(false);CL_TELEFONE_FIXO.setText("");
        CL_CELULAR_1.setEnabled(false);CL_CELULAR_1.setText("");
        CL_CELULAR_2.setEnabled(false);CL_CELULAR_2.setText("");
        CL_CELULAR_3.setEnabled(false);CL_CELULAR_3.setText("");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CL_STATUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CL_STATUSActionPerformed
        if(CL_STATUS.isSelected())
        {
            estado_cliente="1";
            JOptionPane.showMessageDialog(null,"Cliente foi ativado");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Cliente foi Desativado");
            estado_cliente="0";
        }
    }//GEN-LAST:event_CL_STATUSActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CL_NOME.setEnabled(true);
        CL_RG.setEnabled(true);
        CL_CPF.setEnabled(true);
        CL_DATA_NASCIMENTO.setEnabled(true);
        CL_RUA.setEnabled(true);
        CL_NUMERO.setEnabled(true);
        CL_BAIRRO.setEnabled(true);
        CL_CEP.setEnabled(true);
        CL_CIDADE.setEnabled(true);
        CL_ESTADO.setEnabled(true);
        CL_EMAIL.setEnabled(true);
        CL_DATA_CADASTRO.setEnabled(true);
        CL_TELEFONE_FIXO.setEnabled(true);
        CL_CELULAR_1.setEnabled(true);
        CL_CELULAR_2.setEnabled(true);
        CL_CELULAR_3.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaActionPerformed

    }//GEN-LAST:event_btn_pesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_CL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_CL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CL_BAIRRO;
    private javax.swing.JTextField CL_CELULAR_1;
    private javax.swing.JTextField CL_CELULAR_2;
    private javax.swing.JTextField CL_CELULAR_3;
    private javax.swing.JTextField CL_CEP;
    private javax.swing.JTextField CL_CIDADE;
    private javax.swing.JTextField CL_CPF;
    private javax.swing.JTextField CL_DATA_CADASTRO;
    private javax.swing.JFormattedTextField CL_DATA_NASCIMENTO;
    private javax.swing.JTextField CL_EMAIL;
    private javax.swing.JTextField CL_ESTADO;
    private javax.swing.JTextField CL_NOME;
    private javax.swing.JTextField CL_NUMERO;
    private javax.swing.JTextField CL_RG;
    private javax.swing.JTextField CL_RUA;
    private javax.swing.JCheckBox CL_STATUS;
    private javax.swing.JTextField CL_TELEFONE_FIXO;
    private javax.swing.JButton btn_pesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JLabel label_dataNascimento;
    // End of variables declaration//GEN-END:variables
}
