/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 8680213
 */
public class Filme_FL extends javax.swing.JFrame {

public Connection con;
public Statement st;

    /**
     * Creates new form Funcionario
     */
    public Filme_FL() {
        initComponents();
        Conexao FL_Filme = new Conexao();
        FL_Filme.conexao();
        FL_NOME.setEnabled(false);
        FL_DURACAO.setEnabled(false); 
        FL_GENERO.setEnabled(false);
        FL_PRODUTORA.setEnabled(false);
        FL_DIRETOR.setEnabled(false);
        FL_ATOR_PRINCIPAL.setEnabled(false);
        FL_VALOR.setEnabled(false);
        FL_QUANTIDADE.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FL_NOME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CL_DATA_NASCIMENTO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FL_DIRETOR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FL_ATOR_PRINCIPAL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FL_QUANTIDADE = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        FL_GENERO = new javax.swing.JComboBox<>();
        FL_PRODUTORA = new javax.swing.JComboBox<>();
        FL_VALOR = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        FL_DURACAO = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(FL_NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Duração");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Genero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        CL_DATA_NASCIMENTO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CL_DATA_NASCIMENTO.setText("Produtora");
        jPanel1.add(CL_DATA_NASCIMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Valor de Locação");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        jPanel1.add(FL_DIRETOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Diretor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));
        jPanel1.add(FL_ATOR_PRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quantidade");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));
        jPanel1.add(FL_QUANTIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 140, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Código Filme:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jTextField25.setEditable(false);
        jPanel1.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 50, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Ator Principal");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DADOS DO FILME");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 180, 220));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 120, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Alterar");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 130, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Novo  Filme");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 120, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Gravar Filme");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 140, 40));

        FL_GENERO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AÇÃO", "AVENTURA", "COMEDIA", "DRAMA", "FICCÃO CIENTIFICA" }));
        FL_GENERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FL_GENEROActionPerformed(evt);
            }
        });
        jPanel1.add(FL_GENERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, -1));

        FL_PRODUTORA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "DREAMWORKS", "LIONS GATE ENTERTAINMENT", "PARAMOUNT MOTION PICTURES GROUP", "21st CENTUTY FOX", "UNIVERSAL PICTURE", "WALT DISNEY COMPANY" }));
        jPanel1.add(FL_PRODUTORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, -1));

        FL_VALOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "10.00", "15.00", "20.00" }));
        jPanel1.add(FL_VALOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 100, -1));

        jButton1.setText("Conexão SQL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 120, 30));

        try {
            FL_DURACAO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FL_DURACAO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(FL_DURACAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/tela_file5.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipal2 obj = new MenuPrincipal2();
        obj.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            try
            {
            String comando_filme;
        
            comando_filme = "insert into FILME (FL_NOME,FL_DURACAO,FL_GENERO,"
            + "FL_PRODUTORA,FL_DIRETOR,FL_ATOR_PRINCIPAL,FL_VALOR,FL_QUANTIDADE)"
            +"values('"
            +FL_NOME.getText()
            +"','"        
            +FL_DURACAO.getText()
            +"','"        
            +FL_GENERO.getSelectedItem()
            +"','"        
            +FL_PRODUTORA.getSelectedItem()
            +"','"        
            +FL_DIRETOR.getText()
            +"','"        
            +FL_ATOR_PRINCIPAL.getText()
            +"','"        
            +FL_VALOR.getSelectedItem()
            +"','" 
            +FL_QUANTIDADE.getText()
            +"')";
            
            st.executeUpdate(comando_filme);
                JOptionPane.showMessageDialog(null,"Filme Cadastrado com Sucesso");
            }catch(Exception e)
            {
                 JOptionPane.showMessageDialog(null,"Erro ao cadastrar Filme");
            }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void FL_GENEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FL_GENEROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FL_GENEROActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        FL_NOME.setEnabled(true);
        FL_DURACAO.setEnabled(true); 
        FL_GENERO.setEnabled(true);
        FL_PRODUTORA.setEnabled(true);
        FL_DIRETOR.setEnabled(true);
        FL_ATOR_PRINCIPAL.setEnabled(true);
        FL_VALOR.setEnabled(true);
        FL_QUANTIDADE.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filme_FL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filme_FL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CL_DATA_NASCIMENTO;
    private javax.swing.JTextField FL_ATOR_PRINCIPAL;
    private javax.swing.JTextField FL_DIRETOR;
    private javax.swing.JFormattedTextField FL_DURACAO;
    private javax.swing.JComboBox<String> FL_GENERO;
    private javax.swing.JTextField FL_NOME;
    private javax.swing.JComboBox<String> FL_PRODUTORA;
    private javax.swing.JTextField FL_QUANTIDADE;
    private javax.swing.JComboBox<String> FL_VALOR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField25;
    // End of variables declaration//GEN-END:variables
}
