/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javalocadora;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 8680213
 */
public class Funcionario_FCN extends javax.swing.JFrame {

    public Connection con;
    public Statement st;
    public int idfuncionario;
    Conexao FCN_Funcionario = new Conexao ();
    /**
     * Creates new form Filme
     */
    public Funcionario_FCN() {
        initComponents();
       
        FCN_Funcionario.conexao();
        FCN_NOME.setEnabled(false);
        FCN_RG.setEnabled(false);
        FCN_CPF.setEnabled(false);
        FCN_DATA_NASCIMENTO.setEnabled(false);
        FCN_RUA.setEnabled(false);
        FCN_NUMERO.setEnabled(false);
        FCN_BAIRRO.setEnabled(false);
        FCN_CEP.setEnabled(false);
        FCN_CIDADE.setEnabled(false);
        FCN_ESTADO.setEnabled(false);
        FCN_EMAIL.setEnabled(false);
        FCN_TELEFONE_FIXO.setEnabled(false);
        FCN_CELULAR_1.setEnabled(false);
        FCN_CELULAR_2.setEnabled(false);
        FCN_CELULAR_3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FCN_NOME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FCN_RG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FCN_CPF = new javax.swing.JTextField();
        jlabeldn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FCN_BAIRRO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FCN_RUA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FCN_CIDADE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FCN_CEP = new javax.swing.JTextField();
        FCN_EMAIL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FCN_TELEFONE_FIXO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        FCN_CELULAR_3 = new javax.swing.JTextField();
        ID_FUNCIONARIO = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        FCN_NUMERO = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        FCN_ESTADO = new javax.swing.JTextField();
        FCN_CELULAR_2 = new javax.swing.JTextField();
        FCN_CELULAR_1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FCN_DATA_NASCIMENTO = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btn_voltar_FCN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(FCN_NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("RG:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(FCN_RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        jPanel1.add(FCN_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, -1));

        jlabeldn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabeldn.setText("Data Nascimento :");
        jPanel1.add(jlabeldn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        jPanel1.add(FCN_BAIRRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Rua:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        jPanel1.add(FCN_RUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 320, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));
        jPanel1.add(FCN_CIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));
        jPanel1.add(FCN_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 170, -1));
        jPanel1.add(FCN_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Celular");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));
        jPanel1.add(FCN_TELEFONE_FIXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 120, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Telefone Fixo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));
        jPanel1.add(FCN_CELULAR_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 120, -1));

        ID_FUNCIONARIO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID_FUNCIONARIO.setText("Código Funcionário");
        jPanel1.add(ID_FUNCIONARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTextField25.setEditable(false);
        jPanel1.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 50, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Nº");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));
        jPanel1.add(FCN_NUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Estado");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));
        jPanel1.add(FCN_ESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 40, -1));
        jPanel1.add(FCN_CELULAR_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 120, -1));
        jPanel1.add(FCN_CELULAR_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 120, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DADOS PESSOAIS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("ENDEREÇO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CONTATO");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        try {
            FCN_DATA_NASCIMENTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FCN_DATA_NASCIMENTO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(FCN_DATA_NASCIMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Gravar Funcionario");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 140, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Novo Funcionario");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 130, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Alterar");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 80, 30));

        btn_voltar_FCN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltar_FCN.setText("Voltar");
        btn_voltar_FCN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_voltar_FCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_FCNActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar_FCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 80, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, 150));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("FOTO");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 100, 30));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fundo_cliente.jpg"))); // NOI18N
        jLabel20.setAutoscrolls(true);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        idfuncionario += 1;
        
        try{

            PreparedStatement pst =FCN_Funcionario.con.prepareStatement ("insert into funcionario "
            + "(FCN_NOME,FCN_RG,FCN_CPF,"
            + "FCN_DATA_NASCIMENTO,"
            + "FCN_RUA,FCN_NUMERO,"
            + "FCN_BAIRRO,FCN_CEP,FCN_CIDADE,"
            + "FCN_ESTADO,FCN_EMAIL)"
            +"values (?,?,?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1,FCN_NOME.getText());
            pst.setString(2,FCN_RG.getText());
            pst.setString(3,FCN_CPF.getText());
            pst.setString(4,FCN_DATA_NASCIMENTO.getText());
            pst.setString(5,FCN_RUA.getText());
            pst.setString(6,FCN_NUMERO.getText());
            pst.setString(7,FCN_BAIRRO.getText());
            pst.setString(8,FCN_CEP.getText());
            pst.setString(9,FCN_CIDADE.getText());
            pst.setString(10,FCN_ESTADO.getText());
            pst.setString(11,FCN_EMAIL.getText());
             PreparedStatement pstTel = FCN_Funcionario.con.prepareStatement("insert into CLIENTE_TELEFONE (CL_TELEFONE_FIXO,CL_CELULAR_1,"
       +"CL_CELULAR_2,CL_CELULAR_3)VALUES (?,?,?,?)");
       pstTel.setString(1,FCN_TELEFONE_FIXO.getText());
       pstTel.setString(2,FCN_CELULAR_1.getText());
       pstTel.setString(3,FCN_CELULAR_2.getText());
       pstTel.setString(4,FCN_CELULAR_3.getText());
            
            pst.executeUpdate();
            pstTel.executeUpdate();
            JOptionPane.showMessageDialog(null,"Cliente Cadastrado com Sucesso!");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERRO NA INSERÇÃO \n : " +e);
        }
        FCN_NOME.setEnabled(false);FCN_NOME.setText("");
        FCN_RG.setEnabled(false);FCN_RG.setText("");
        FCN_CPF.setEnabled(false);FCN_CPF.setText("");
        FCN_DATA_NASCIMENTO.setEnabled(false);FCN_DATA_NASCIMENTO.setText("");
        FCN_RUA.setEnabled(false);FCN_RUA.setText("");
        FCN_NUMERO.setEnabled(false);FCN_NUMERO.setText("");
        FCN_BAIRRO.setEnabled(false);FCN_BAIRRO.setText("");
        FCN_CEP.setEnabled(false);FCN_CEP.setText("");
        FCN_CIDADE.setEnabled(false);FCN_CIDADE.setText("");
        FCN_ESTADO.setEnabled(false);FCN_ESTADO.setText("");
        FCN_EMAIL.setEnabled(false);FCN_EMAIL.setText("");
        FCN_TELEFONE_FIXO.setEnabled(false);FCN_TELEFONE_FIXO.setText("");
        FCN_CELULAR_1.setEnabled(false);FCN_CELULAR_1.setText("");
        FCN_CELULAR_2.setEnabled(false);FCN_CELULAR_2.setText("");
        FCN_CELULAR_3.setEnabled(false);FCN_CELULAR_3.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_voltar_FCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_FCNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipal2 obj = new MenuPrincipal2();
        obj.setVisible(true);

    }//GEN-LAST:event_btn_voltar_FCNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        FCN_NOME.setEnabled(true);
        FCN_RG.setEnabled(true);
        FCN_CPF.setEnabled(true);
        FCN_DATA_NASCIMENTO.setEnabled(true);
        FCN_RUA.setEnabled(true);
        FCN_NUMERO.setEnabled(true);
        FCN_BAIRRO.setEnabled(true);
        FCN_CEP.setEnabled(true);
        FCN_CIDADE.setEnabled(true);
        FCN_ESTADO.setEnabled(true);
        FCN_EMAIL.setEnabled(true);
        FCN_TELEFONE_FIXO.setEnabled(true);
        FCN_CELULAR_1.setEnabled(true);
        FCN_CELULAR_2.setEnabled(true);
        FCN_CELULAR_3.setEnabled(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario_FCN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario_FCN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FCN_BAIRRO;
    private javax.swing.JTextField FCN_CELULAR_1;
    private javax.swing.JTextField FCN_CELULAR_2;
    private javax.swing.JTextField FCN_CELULAR_3;
    private javax.swing.JTextField FCN_CEP;
    private javax.swing.JTextField FCN_CIDADE;
    private javax.swing.JTextField FCN_CPF;
    private javax.swing.JFormattedTextField FCN_DATA_NASCIMENTO;
    private javax.swing.JTextField FCN_EMAIL;
    private javax.swing.JTextField FCN_ESTADO;
    private javax.swing.JTextField FCN_NOME;
    private javax.swing.JTextField FCN_NUMERO;
    private javax.swing.JTextField FCN_RG;
    private javax.swing.JTextField FCN_RUA;
    private javax.swing.JTextField FCN_TELEFONE_FIXO;
    private javax.swing.JLabel ID_FUNCIONARIO;
    private javax.swing.JButton btn_voltar_FCN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JLabel jlabeldn;
    // End of variables declaration//GEN-END:variables
}
